### ISSUE TITLE
Encrypt high score

### ISSUE THREAD

**Issue by americast** [americast/Snakes#5]
The high score is stored as plain text. Encrypt it, preferably with SHA-256 (because, why not :wink: ? )

**Comment by rishabhdeepsingh** [comment]
Can we use Qt Framework to encrypt?

**Comment by americast** [comment]
Thanks for your interest @rishabhdeepsingh. SHA can be implemented without any external libraries. A direct implementation in C++ is suggested.

**Comment by rishabhdeepsingh** [comment]
Can we use a Simple Encryption as sha256 is hard to Encrypt and decrypt?

**Comment by americast** [comment]
Well @rishabhdeepsingh, you cannot decrypt SHA :sweat_smile:. 
SHA is pretty standard and it is not so difficult to encrypt with SHA. So, I guess we should stick to it. If required, in place of SHA-256, you may use SHA-1. What other simple encryption method are you aware of?

**Comment by rishabhdeepsingh** [comment]
well, we need to decrypt also to compare to recent high scores.

**Comment by americast** [comment]
@rishabhdeepsingh It's not possible to decrypt SHA. So, we shall not decrypt the high score.

**Comment by rishabhdeepsingh** [comment]
Then how are we going to Compare our High Scores with the score of the recent game?

**Comment by JiviteshDebata** [comment]
Make it non decryptable might render it useless. But since we are using a hashing method shall we do this? 
1) make score file binary so it is not saved as plain text
2) ask user for a password (never store it ofcourse )
3) make a hash of it using SHA 256 (store this)
4) next time another user plays ask them to enter password. If hash matches allow modification of highscore.

It achieves the security of making it non readable by humans 
and it uses SHA 256 hashing so as to make a robust passcode system

**Comment by JiviteshDebata** [comment]
However if we **have  to** encrypt that file then
1) make score file binary 
2) get password from user
3)make hash of it using SHA 256
4) use that hash as key to encrypt high score file (key for AES or any other encrypting algorithm ?) 
5) next user asked for password 
6)see if hash generated decrypts  the high score file (keep readable known token at EOF) 
7) allow modification of it

**Comment by JiviteshDebata** [comment]
PR made to simply make score file binary 
ETA on SHA-256 implementation and AES is probably two days at max

**Comment by americast** [comment]
@rishabhdeepsingh You don't decrypt an SHA. You run a loop from 0 to some finite number, making SHAs and keep comparing it to the stored SHA. As soon as they match, you get the high score.

Suggestion by @JiviteshDebata also looks good. Let's stick to this for now.

**Comment by JiviteshDebata** [comment]
@americast  SHA256 generating code PR made. Hash generated can be used for anything
